=== alexmihaimzh/ikasan/ikasaneip/sample/spring-boot/component-factory/src/main/resources/xsd/adjusted-book-prices.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="AdjustedBooks" type="BooksForm"/>

    <xsd:complexType name="BooksForm">
        <xsd:sequence>
            <xsd:element name="AdjustedBook"
                         type="BookForm"
                         minOccurs="0"
                         maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="BookForm">
        <xsd:sequence>
            <xsd:element name="Author"   type="xsd:string"/>
            <xsd:element name="Title"    type="xsd:string"/>
            <xsd:element name="Genre"    type="xsd:string"/>
            <xsd:element name="Price"    type="xsd:float" />
            <xsd:element name="PubDate" type="xsd:date" />
            <xsd:element name="Review"   type="xsd:string"/>
        </xsd:sequence>
        <xsd:attribute name="id"   type="xsd:string"/>
    </xsd:complexType>
</xsd:schema>

=== alexmihaimzh/ikasan/ikasaneip/component-factory/test-module/jar/src/test/resources/increaseBookPricesJmsToSftpFlow/expected-adjusted-books.xml
<?xml version="1.0" encoding="UTF-8"?>
<AdjustedBooks xmlns:x="http://www.bookprices.com/xsd/book-prices.xsd"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.bookprices.com/xsd/adjusted-book-prices.xsd">
    <AdjustedBook id="bk001">
        <Author>Writer</Author>
        <Title>The First Book</Title>
        <Genre>Fiction</Genre>
        <Price>49.45</Price>
        <PubDate>2000-10-01</PubDate>
        <Review>An amazing story of nothing.</Review>
    </AdjustedBook>
    <AdjustedBook id="bk002">
        <Author>Poet</Author>
        <Title>The Poet's First Poem</Title>
        <Genre>Poem</Genre>
        <Price>27.44</Price>
        <PubDate>2000-10-01</PubDate>
        <Review>Least poetic poems.</Review>
    </AdjustedBook>
</AdjustedBooks>
